(function(g){var window=this;var mqa=function(a,b){return g.Wb(a,b)},E5=function(a,b,c){a.l.set(b,c)},F5=function(a){E5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},G5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.Wm(a.l,b,c)},nqa=function(a,b){var c=[];
g.Zi(b,function(d){try{var e=g.$n.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.Zn(e)&&c.push(d):c.push(d)},a);
return c},oqa=function(a,b){var c=nqa(a,b);
(0,g.A)(c,function(d){g.$n.prototype.remove.call(this,d)},a)},H5=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},pqa=function(a,b){g.ab(a,b)||a.push(b)},I5=function(a){var b=0,c;
for(c in a)b++;return b},J5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},K5=function(){},qqa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},rqa=function(a){if(a.Ec&&"function"==typeof a.Ec)return a.Ec();
if(g.u(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Sb(a)},sqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.u(a))(0,g.A)(a,b,void 0);else{if(a.Pd&&"function"==typeof a.Pd)var c=a.Pd();else if(a.Ec&&"function"==typeof a.Ec)c=void 0;else if(g.La(a)||g.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Tb(a);d=rqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},tqa=function(a,b,c,d){var e=new g.Km(null,void 0);
a&&g.Lm(e,a);b&&g.Mm(e,b);c&&g.Nm(e,c);d&&(e.i=d);return e},L5=function(a,b){g.cp[a]=!0;
var c=g.ap();c&&c.publish.apply(c,arguments);g.cp[a]=!1},M5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Hm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",uqa(this,a.capabilities||""),vqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},uqa=function(a,b){a.capabilities.clear();
(0,g.Wd)(b.split(","),g.Qa(mqa,wqa)).forEach(function(c){a.capabilities.add(c)})},vqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},N5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},O5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},P5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},xqa=function(a){return new N5(a)},Q5=function(a){return g.Ka(a)?(0,g.B)(a,xqa):[]},R5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},S5=function(a){return g.Ka(a)?"["+(0,g.B)(a,R5).join(",")+"]":"null"},T5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},yqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},U5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},V5=function(a,b){return g.Ya(a,function(c){return O5(c,b)})},W5=function(a){try{var b=(0,g.Rs)(),c=(0,g.Qs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},zqa=function(){var a=(0,g.Qs)();
a&&oqa(a,a.g.lf(!0))},X5=function(){var a=g.Ts("yt-remote-connected-devices")||[];
g.rb(a);return a},Aqa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Y5=function(a){g.Ss("yt-remote-connected-devices",a,86400)},$5=function(){if(Z5)return Z5;
var a=g.Ts("yt-remote-device-id");a||(a=T5(),g.Ss("yt-remote-device-id",a,31536E3));for(var b=X5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return Z5=d},a6=function(){var a=X5(),b=$5();
g.ab(a,b);g.Us()&&g.tb(a,b);a=Aqa(a);if(g.bb(a))try{g.Mr("remote_sid")}catch(c){}else try{g.Lr("remote_sid",a.join(","),-1)}catch(c){}},b6=function(){return g.Ts("yt-remote-session-browser-channel")},c6=function(){return g.Ts("yt-remote-local-screens")||[]},d6=function(){g.Ss("yt-remote-lounge-token-expiration",!0,86400)},Bqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(c6(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.fh)(c,function(d){return!g.ab(b,d)})&&d6();
g.Ss("yt-remote-local-screens",a,31536E3)},Cqa=function(a,b){g.Ss("yt-remote-session-browser-channel",a);
g.Ss("yt-remote-session-screen-id",b);var c=X5(),d=$5();g.ab(c,d)||c.push(d);Y5(c);a6()},e6=function(a){a||(W5("yt-remote-session-screen-id"),W5("yt-remote-session-video-id"));
a6();a=X5();g.eb(a,$5());Y5(a)},g6=function(){if(!f6){var a=g.ko();
a&&(f6=new g.Un(a))}return f6?!!f6.get("yt-remote-use-staging-server"):!1},h6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},i6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},k6=function(a){a.length?j6(a.shift(),function(){k6(a)}):l6()},Dqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},j6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},l6=function(){var a=i6();
a&&a(!1,"No cast extension found")},m6=function(){if(Eqa){var a=2,b=i6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;j6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",l6,c)}},Fqa=function(){m6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);k6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},n6=function(a,b,c){g.H.call(this);
this.B=null!=c?(0,g.y)(a,c):a;this.Wc=b;this.A=(0,g.y)(this.qD,this);this.g=!1;this.i=0;this.l=this.Ca=null;this.o=[]},o6=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return qqa(a)},p6=function(){},q6=function(){},r6=function(){},t6=function(a){return(a=s6(a))?new ActiveXObject(a):new XMLHttpRequest},s6=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},u6=function(a,b,c,d){this.g=a;
this.l=b;this.D=c;this.B=d||1;this.o=45E3;this.ca=new g.vY(this);this.i=new g.bl;this.i.setInterval(250)},w6=function(a,b,c){a.Yh=1;
a.Wf=F5(b.clone());a.ph=c;a.A=!0;v6(a,null)},x6=function(a,b,c,d,e){a.Yh=1;
a.Wf=F5(b.clone());a.ph=null;a.A=c;e&&(a.rA=!1);v6(a,d)},v6=function(a,b){a.Di=(0,g.D)();
y6(a);a.Bg=a.Wf.clone();G5(a.Bg,"t",a.B);a.bl=0;a.sc=a.g.Pp(a.g.Ok()?b:null);0<a.zq&&(a.Tn=new g.el((0,g.y)(a.rB,a,a.sc),a.zq));a.ca.ea(a.sc,"readystatechange",a.hM);var c=a.Xg?g.dc(a.Xg):{};a.ph?(a.Eo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Bg,a.Eo,a.ph,c)):(a.Eo="GET",a.rA&&!g.Md&&(c.Connection="close"),a.sc.send(a.Bg,a.Eo,null,c));a.g.ye(1)},F6=function(a,b,c){for(var d=!0;!a.Mg&&a.bl<c.length;){var e=Gqa(a,c);
if(e==z6){4==b&&(a.ng=4,A6(15),d=!1);break}else if(e==B6){a.ng=4;A6(16);d=!1;break}else C6(a,e)}4==b&&0==c.length&&(a.ng=1,A6(17),d=!1);a.ze=a.ze&&d;d||(D6(a),E6(a))},Gqa=function(a,b){var c=a.bl,d=b.indexOf("\n",c);
if(-1==d)return z6;c=Number(b.substring(c,d));if(isNaN(c))return B6;d+=1;if(d+c>b.length)return z6;var e=b.substr(d,c);a.bl=d+c;return e},I6=function(a,b){a.Di=(0,g.D)();
y6(a);var c=b?window.location.hostname:"";a.Bg=a.Wf.clone();E5(a.Bg,"DOMAIN",c);E5(a.Bg,"t",a.B);try{a.De=new ActiveXObject("htmlfile")}catch(n){D6(a);a.ng=7;A6(22);E6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in G6)k=G6[l];else if(l in H6)k=G6[l]=H6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
G6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.sc("b/12014412"),d+"</body></html>");a.De.open();a.De.write(g.Nc(c));a.De.close();a.De.parentWindow.m=(0,g.y)(a.xL,a);a.De.parentWindow.d=(0,g.y)(a.Az,a,!0);a.De.parentWindow.rpcClose=(0,g.y)(a.Az,a,!1);c=a.De.createElement("DIV");a.De.parentWindow.document.body.appendChild(c);d=g.Dc(a.Bg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.sc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.ye(1)},y6=function(a){a.At=(0,g.D)()+a.o;
J6(a,a.o)},J6=function(a,b){if(null!=a.Ti)throw Error("WatchDog timer not null");
a.Ti=K6((0,g.y)(a.HL,a),b)},L6=function(a){a.Ti&&(g.w.clearTimeout(a.Ti),a.Ti=null)},E6=function(a){a.g.xw()||a.Mg||a.g.In(a)},D6=function(a){L6(a);
g.Ci(a.Tn);a.Tn=null;a.i.stop();g.xY(a.ca);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.De&&(a.De=null)},C6=function(a,b){try{a.g.uz(a,b),a.g.ye(4)}catch(c){}},N6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;M6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){N6(a,b,c,d,f)},f)})}},M6=function(a,b,c){var d=new Image;
d.onload=function(){try{O6(d),c(!0)}catch(e){}};
d.onerror=function(){try{O6(d),c(!1)}catch(e){}};
d.onabort=function(){try{O6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{O6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
J5(d,a)},O6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},P6=function(a){this.g=a;
this.i=new p6},R6=function(a){var b=Q6(a.g,a.fj,"/mail/images/cleardot.gif");
F5(b);N6(b.toString(),5E3,(0,g.y)(a.wC,a),3,2E3);a.ye(1)},T6=function(a){var b=a.g.G;
if(null!=b)A6(5),b?(A6(11),S6(a.g,a,!1)):(A6(12),S6(a.g,a,!0));else if(a.Gd=new u6(a,void 0,void 0,void 0),a.Gd.Xg=a.xq,b=a.g,b=Q6(b,b.Ok()?a.Jj:null,a.yq),A6(5),!g.Kd||g.nd(10))G5(b,"TYPE","xmlhttp"),x6(a.Gd,b,!1,a.Jj,!1);else{G5(b,"TYPE","html");var c=a.Gd;a=!!a.Jj;c.Yh=3;c.Wf=F5(b.clone());I6(c,a)}},U6=function(a){g.rk.call(this);
this.headers=new g.Hm;this.N=a||null;this.i=!1;this.S=this.g=null;this.Z=this.F="";this.A=0;this.l="";this.o=this.aa=this.D=this.R=!1;this.B=0;this.G=null;this.X="";this.J=this.T=!1},Hqa=function(a){return g.Kd&&g.ld(9)&&g.Fa(a.timeout)&&g.Da(a.ontimeout)},Iqa=function(a){return"content-type"==a.toLowerCase()},X6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.A=5;V6(a);W6(a)},V6=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},$6=function(a){if(a.i&&"undefined"!=typeof g.BY)if(a.S[1]&&4==Y6(a)&&2==a.getStatus())Z6(a,"Local request error detected and ignored");
else if(a.D&&4==Y6(a))g.cl(a.zw,0,a);else if(a.dispatchEvent("readystatechange"),4==Y6(a)){Z6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.uf(1,String(a.F));if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Jqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<Y6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";V6(a)}}finally{W6(a)}}},W6=function(a,b){if(a.g){a7(a);
var c=a.g,d=a.S[0]?g.Ha:null;a.g=null;a.S=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},a7=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.G&&(g.w.clearTimeout(a.G),a.G=null)},Y6=function(a){return a.g?a.g.readyState:0},b7=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Z6=function(a,b){return b+" ["+a.Z+" "+a.F+" "+a.getStatus()+"]"},c7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.A=new p6;this.F=a||null;this.G=null!=b?b:null;this.B=c||!1},Kqa=function(a,b){this.g=a;
this.map=b;this.context=null},d7=function(a){g.Tj.call(this,"statevent",a)},e7=function(a,b){g.Tj.call(this,"timingevent",a);
this.size=b},f7=function(a){g.Tj.call(this,"serverreachability",a)},j7=function(a){g7(a);
if(3==a.g){var b=a.rk++,c=a.gm.clone();E5(c,"SID",a.l);E5(c,"RID",b);E5(c,"TYPE","terminate");h7(a,c);b=new u6(a,a.l,b,void 0);b.Yh=2;b.Wf=F5(c.clone());J5(new Image,b.Wf.toString());b.Di=(0,g.D)();y6(b)}i7(a)},l7=function(a){a.RC(1,0);
a.gm=Q6(a,null,a.wq);k7(a)},g7=function(a){a.dg&&(a.dg.abort(),a.dg=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.mf&&(g.w.clearTimeout(a.mf),a.mf=null);m7(a);a.Cd&&(a.Cd.cancel(),a.Cd=null);a.lg&&(g.w.clearTimeout(a.lg),a.lg=null)},n7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Kqa(a.MH++,b));2!=a.g&&3!=a.g||k7(a)},k7=function(a){a.Cd||a.lg||(a.lg=K6((0,g.y)(a.zz,a),0),a.Rh=0)},q7=function(a,b){if(1==a.g){if(!b){a.rk=Math.floor(1E5*Math.random());
var c=a.rk++,d=new u6(a,"",c,void 0);d.Xg=null;var e=o7(a),f=a.gm.clone();E5(f,"RID",c);E5(f,"CVER","1");h7(a,f);w6(d,f,e);a.Cd=d;a.g=2}}else 3==a.g&&(b?p7(a,b):0==a.i.length||a.Cd||p7(a))},p7=function(a,b){if(b)if(6<a.Ng){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.rk-1;var d=o7(a)}else c=b.D,d=b.ph;else c=a.rk++,d=o7(a);var e=a.gm.clone();E5(e,"SID",a.l);E5(e,"RID",c);E5(e,"AID",a.li);h7(a,e);c=new u6(a,a.l,c,a.Rh+1);c.Xg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Cd=c;w6(c,e,d)},h7=function(a,b){if(a.Tc){var c=a.Tc.Vv();
c&&g.Lb(c,function(d,e){E5(b,e,d)})}},o7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Ng&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Ng?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},r7=function(a){a.Rb||a.mf||(a.D=1,a.mf=K6((0,g.y)(a.yz,a),0),a.Kh=0)},t7=function(a){if(a.Rb||a.mf||3<=a.Kh)return!1;
a.D++;a.mf=K6((0,g.y)(a.yz,a),s7(a,a.Kh));a.Kh++;return!0},S6=function(a,b,c){a.Co=c;
a.Ie=b.Af;a.B||l7(a)},m7=function(a){null!=a.Rg&&(g.w.clearTimeout(a.Rg),a.Rg=null)},s7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},v7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.LM,a);c||(c=new g.Km("//www.google.com/images/cleardot.gif"),F5(c));M6(c.toString(),1E4,d)}else A6(2);u7(a,b)},u7=function(a,b){a.g=0;
a.Tc&&a.Tc.Su(b);i7(a);g7(a)},i7=function(a){a.g=0;
a.Ie=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Cp();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Tc.Cp(b)}},Q6=function(a,b,c){var d=g.Sm(c);
if(""!=d.g)b&&g.Mm(d,b+"."+d.g),g.Nm(d,d.A);else{var e=window.location;d=tqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.sj&&g.Lb(a.sj,function(f,k){E5(d,k,f)});
E5(d,"VER",a.Ng);h7(a,d);return d},K6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},A6=function(a){w7.dispatchEvent(new d7(w7,a))},x7=function(){},y7=function(){this.g=[];
this.i=[]},Lqa=function(a,b){this.action=a;
this.params=b||{}},z7=function(a,b){g.H.call(this);
this.g=new g.K(this.pL,0,this);g.J(this,this.g);this.Wc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},A7=function(a,b,c){this.I=a;
this.B=b;this.l=new g.Tn;this.i=new z7(this.rM,this);this.g=null;this.ib=!1;this.A=null;this.G="";this.F=this.o=0;this.D=[];this.J=c||!1},Mqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Co,sessionId:a.g.l,arrayId:a.g.li}},B7=function(a,b){a.F=b||0;
a.i.stop();a.g&&(3==a.g.g&&q7(a.g),j7(a.g));a.F=0},C7=function(a){return!!a.g&&3==a.g.g},Nqa=function(a,b){(a.B.loungeIdToken=b)||a.i.stop()},D7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.uf(4,a))||"";b&&(this.port=":"+b);this.domain=g.vf(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},E7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ef(c+b,{})},F7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),Ud:g.Qa(a.A,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Vp(b,a)},Oqa=function(){var a=G7;
H7();I7.push(a);J7(I7)},K7=function(a,b){H7();
var c=I7,d=Pqa(a,String(b));g.bb(c)?Qqa(d):(J7(c),(0,g.A)(c,function(e){e(d)}))},H7=function(){I7||(I7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",I7,void 0))},Qqa=function(a){var b=(L7+1)%50;
L7=b;M7[b]=a;N7||(N7=49==b)},J7=function(a){var b=M7;
if(b[0]){var c=L7,d=N7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(f){f(e)})}while(d!=c);
M7=Array(50);L7=-1;N7=!1}},Pqa=function(a,b){var c=((0,g.D)()-Rqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O7=function(a){g.O.call(this);
this.D=a;this.g=[]},P7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Sqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Wd)(a.g,function(f){return!!U5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=P7(a,b[d])||c;return c},Tqa=function(a,b){var c=a.g.length;
a.g=(0,g.Wd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},Q7=function(a,b,c,d){g.O.call(this);
this.B=a;this.A=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ca=NaN},S7=function(a){O7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;R7(this);this.info("Initializing with "+S5(this.g))},Uqa=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=E7(a.l,"/pairing/get_lounge_token_batch");
F7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.AD,a),(0,g.y)(a.zD,a))}},R7=function(a){var b=Q5(c6());
b=(0,g.Wd)(b,function(c){return!c.uuid});
return Sqa(a,b)},T7=function(a,b){Bqa((0,g.B)(a.g,P5));
b&&d6()},V7=function(a,b){g.O.call(this);
this.B=b;var c=g.Ts("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.B(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.A=a;this.l=this.o=NaN;this.i=null;U7("Initialized with "+g.tm(this.g))},Vqa=function(a,b,c){var d=E7(a.A,"/pairing/get_screen_availability");
F7(a.A,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},W7=function(a,b){a:if(I5(b)!=I5(a.g))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(U7("Updated online screens: "+g.tm(a.g)),a.g=b,a.O("screenChange"));Wqa(a)},X7=function(a){isNaN(a.l)||g.$o(a.l);
a.l=g.Yo((0,g.y)(a.Fs,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},U7=function(a){K7("OnlineScreenService",a)},Xqa=function(a){var b={};
(0,g.A)(a.B(),function(c){c.token?b[c.token]=c.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},Wqa=function(a){a=g.Tb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.Ss("yt-remote-online-screen-ids",a.join(","),60):W5("yt-remote-online-screen-ids")},Y7=function(a){O7.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.o=[];this.A={};Yqa(this)},$qa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.A[b]);var k=a.Qd();if(k=(c?V5(k,c):null)||V5(k,b)){k.uuid=b;var l=Z7(a,k);Vqa(a.i,l,function(m){e(m?l:null)})}else c?Zqa(a,c,(0,g.y)(function(m){var n=Z7(this,new N5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Vqa(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},ara=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Zqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Vp(E7(a.B,"/pairing/get_lounge_token_batch"),e)},bra=function(a){a.g=a.l.Qd();
var b=a.A,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+S5(a.g))},Yqa=function(a){$7(a);
a.l=new S7(a.B);a.l.subscribe("screenChange",(0,g.y)(a.ID,a));bra(a);a.o=Q5(g.Ts("yt-remote-automatic-screen-cache")||[]);$7(a);a.info("Initializing automatic screens: "+S5(a.o));a.i=new V7(a.B,(0,g.y)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.O("onlineScreenChange")},a))},Z7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=V5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Ss("yt-remote-automatic-screen-cache",(0,g.B)(a.o,P5)));$7(a);a.A[b.uuid]=b.id;g.Ss("yt-remote-device-id-map",a.A,31536E3);return b},$7=function(a){a.A=g.Ts("yt-remote-device-id-map")||{}},a8=function(a,b,c){g.O.call(this);
this.S=c;this.G=a;this.i=b;this.l=null},b8=function(a,b){K7(a.S,b)},c8=function(a,b){a8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.B=(0,g.y)(this.tN,this);this.A=(0,g.y)(this.SL,this);this.o=g.Yo((0,g.y)(function(){cra(this,null)},this),12E4)},dra=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.tm(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){b8(this,"Failed to send message: getMdxSessionStatus.")},a)):b8(a,"Sending yt message without session: "+g.tm(b))},cra=function(a,b){g.$o(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Kn,a),d=(0,g.y)(a.Td,a);a.nw(b,c,d,5)}}else a.Td(Error("Waiting for session status timed out."))},d8=function(a,b,c){a8.call(this,a,b,"DialSession");
this.o=this.F=null;this.I="";this.N=c;this.A=null;this.D=g.Ha;this.B=NaN;this.J=(0,g.y)(this.wN,this);this.g=g.Ha},era=function(a){a.g=a.G.wB(a.I,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.Kn(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Td(b)},a))},fra=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.A){var c=a.A.currentTime||0;b.v=a.A.videoId;b.t=c}g6()&&(b.env_useStageMdx=1);return g.Cf(b)},e8=function(a,b){a8.call(this,a,b,"ManualSession");
this.g=g.Yo((0,g.y)(this.mi,this,null),150)},f8=function(a,b,c,d){g.O.call(this);
this.i=a;this.D=b||"233637DE";this.B=c||"cl";this.F=d||!1;this.g=null;this.A=!1;this.l=[];this.o=(0,g.y)(this.xK,this)},gra=function(a,b){return b?g.Ya(a.l,function(c){return O5(b,c.label)},a):null},g8=function(a){K7("Controller",a)},G7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},h8=function(a){return a.A||!!a.l.length||!!a.g},i8=function(a,b,c){b!=a.g&&(g.Ci(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.xz,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.O("yt-remote-cast2-session-change",null))},hra=function(a){var b=a.i.vB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&O5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=gra(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},nra=function(a,b,c,d,e,f,k){ira()?jra(b,e,f,k)&&(k8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?kra(a,c):(window.__onGCastApiAvailable=function(l,m){l?kra(a,c):(l8("Failed to load cast API: "+m),m8(!1),k8(!1),W5("yt-remote-cast-available"),W5("yt-remote-cast-receiver"),lra(),c(!1))},d?g.kp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Fqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?l6():(m6(),k6(mra.map(Dqa))))):j8("Cannot initialize because not running Chrome")},lra=function(){j8("dispose");
var a=n8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);ora(!1);g.fp(o8);o8.length=0},p8=function(){return!!g.Ts("yt-remote-cast-installed")},pra=function(){var a=g.Ts("yt-remote-cast-receiver");
return a?a.friendlyName:null},qra=function(){j8("clearCurrentReceiver");
W5("yt-remote-cast-receiver")},rra=function(){return p8()?n8()?n8().getCastSession():(l8("getCastSelector: Cast is not initialized."),null):(l8("getCastSelector: Cast API is not installed!"),null)},r8=function(){p8()?n8()?q8()?(j8("Requesting cast selector."),n8().requestSession()):(j8("Wait for cast API to be ready to request the session."),o8.push(g.ep("yt-remote-cast2-api-ready",r8))):l8("requestCastSelector: Cast is not initialized."):l8("requestCastSelector: Cast API is not installed!")},s8=
function(a,b){q8()?n8().setConnectedScreenStatus(a,b):l8("setConnectedScreenStatus called before ready.")},ira=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Iw||a},sra=function(a,b){n8().init(a,b)},jra=function(a,b,c,d){var e=!1;
n8()||(a=new f8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ss("yt-remote-cast-available",f);L5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){j8("onReceiverSelected: "+f.friendlyName);
g.Ss("yt-remote-cast-receiver",f);L5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){j8("onReceiverResumed: "+f.friendlyName);
g.Ss("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){j8("onSessionChange: "+R5(f));
f||W5("yt-remote-cast-receiver");L5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
j8("cloudview.createSingleton_: "+e);return e},n8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},kra=function(a,b){m8(!0);
k8(!1);sra(a,function(c){c?(ora(!0),g.hp("yt-remote-cast2-api-ready")):(l8("Failed to initialize cast API."),m8(!1),W5("yt-remote-cast-available"),W5("yt-remote-cast-receiver"),lra());b(c)})},j8=function(a){K7("cloudview",a)},l8=function(a){K7("cloudview",a)},m8=function(a){j8("setCastInstalled_ "+a);
g.Ss("yt-remote-cast-installed",a)},q8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},ora=function(a){j8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},k8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},t8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.B=this.D=0;this.g=null;this.hasNext=this.Je=!1;this.G=this.F=this.i=this.o=0;this.l=NaN;this.A=!1;this.reset(a)},u8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Je=!1;a.hasNext=!1;a.D=0;a.B=(0,g.D)();a.o=0;a.i=0;a.F=0;a.G=0;a.l=NaN;a.A=!1},v8=function(a){return 1==a.playerState?((0,g.D)()-a.B)/1E3:0},w8=function(a,b){a.D=b;
a.B=(0,g.D)()},x8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.B)/1E3+a.D;
case -1E3:return 0}return a.D},y8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&u8(a)},z8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.g);b.hasPrevious=a.Je;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.B;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.F;b.loadedTime=a.G;b.liveIngestionTime=a.l;return b},B8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.B=[];this.A=new y7;this.l=this.i=null;this.G=(0,g.y)(this.uI,this);this.D=(0,g.y)(this.vk,this);this.F=(0,g.y)(this.tI,this);this.I=(0,g.y)(this.II,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Dt,this),tra(this))):c=3;0!=c&&(b?this.Dt(c):g.Yo((0,g.y)(function(){this.Dt(c)},this),0));
var d=rra();d&&A8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},C8=function(a){return new t8(a.o.getPlayerContextData())},tra=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.B.push(this.o.subscribe(b,g.Qa(this.uK,b),this))},a)},ura=function(a){(0,g.A)(a.B,function(b){this.o.unsubscribeByKey(b)},a);
a.B.length=0},D8=function(a,b){var c=a.A;
50>c.g.length+c.i.length&&a.A.i.push(b)},F8=function(a,b,c){var d=C8(a);
w8(d,c);-1E3!=d.playerState&&(d.playerState=b);E8(a,d)},G8=function(a,b,c){a.o.sendMessage(b,c)},E8=function(a,b){ura(a);
a.o.setPlayerContextData(z8(b));tra(a)},A8=function(a,b){a.l&&(a.l.removeUpdateListener(a.G),a.l.removeMediaListener(a.D),a.vk(null));
a.l=b;a.l&&(K7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.G),a.l.addMediaListener(a.D),a.l.media.length&&a.vk(a.l.media[0]))},vra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=C8(a);b.contentId!=d.videoId&&K7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;w8(d,a.i.getEstimatedTime());E8(a,d)}else K7("CP","No cast media video. Ignoring state update.")},H8=function(a,b,c){return(0,g.y)(function(d){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),G8(this,b,c))},a)},I8=function(a,b,c){g.O.call(this);
this.A=NaN;this.J=!1;this.F=this.D=this.G=this.I=NaN;this.S=[];this.o=this.B=this.l=this.Oa=this.g=null;this.R=a;this.S.push(g.qr(window,"beforeunload",(0,g.y)(this.tD,this)));this.i=[];this.Oa=new t8;this.N=b.id;this.g=wra(this,c);this.g.subscribe("handlerOpened",this.yI,this);this.g.subscribe("handlerClosed",this.vI,this);this.g.subscribe("handlerError",this.wI,this);this.g.subscribe("handlerMessage",this.xI,this);Nqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.Us()&&g.Ss("yt-remote-session-video-id",d)},this)},J8=function(a){K7("conn",a)},wra=function(a,b){return new A7(E7(a.R,"/bc"),b)},K8=function(a,b){a.O("proxyStateChange",b)},xra=function(a){a.A=g.Yo((0,g.y)(function(){J8("Connecting timeout");
this.Oh(1)},a),2E4)},L8=function(a){g.$o(a.A);
a.A=NaN},M8=function(a){g.$o(a.I);
a.I=NaN},yra=function(a){N8(a);
a.G=g.Yo((0,g.y)(function(){O8(this,"getNowPlaying")},a),2E4)},N8=function(a){g.$o(a.G);
a.G=NaN},Ara=function(a,b){b&&(L8(a),M8(a));
b==(C7(a.g)&&isNaN(a.A))?b&&(K8(a,1),O8(a,"getSubtitlesTrack")):b?(a.lw()&&a.Oa.reset(),K8(a,1),O8(a,"getNowPlaying"),zra(a)):a.Oh(1)},Bra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Zb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.O("remotePlayerChange"))},Cra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;y8(a.Oa,c,d);a.O("remoteQueueChange")},Era=function(a,b){b.params=b.params||{};
Cra(a,b);Dra(a,b);a.O("autoplayDismissed")},Dra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
w8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.G=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.F=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.A=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?yra(a):N8(a);a.O("remotePlayerChange")},Fra=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);w8(a.Oa,isNaN(c)?0:c);a.O("remotePlayerChange")}},Gra=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.O("remotePlayerChange")},Hra=function(a,b){a.B=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},Ira=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Je="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.O("previousNextChange")},zra=function(a){g.$o(a.F);
a.F=g.Yo((0,g.y)(a.Oh,a,1),864E5)},O8=function(a,b,c){c?J8("Sending: action="+b+", params="+g.tm(c)):J8("Sending: action="+b);
a.g.sendMessage(b,c)},P8=function(a){O7.call(this,"ScreenServiceProxy");
this.Vc=a;this.i=[];this.i.push(this.Vc.$_s("screenChange",(0,g.y)(this.rN,this)));this.i.push(this.Vc.$_s("onlineScreenChange",(0,g.y)(this.ZJ,this)))},Nra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Qo("MDX_CONFIG")||b;zqa();a6();Q8||(Q8=new D7(b?b.loungeApiHost:void 0),g6()&&(Q8.g="/api/loungedev"));R8||(R8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",R8,void 0));Jra();var c=S8();if(!c){var d=new Y7(Q8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=S8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);nra(a,d,function(m){m?T8()&&s8(T8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){L5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),U8("Initializing: "+g.tm(b)),V8.push(g.ep("yt-remote-cast2-availability-change",function(){L5("yt-remote-receiver-availability-change")})),V8.push(g.ep("yt-remote-cast2-receiver-selected",function(){W8(null);
L5("yt-remote-auto-connect","cast-selector-receiver")})),V8.push(g.ep("yt-remote-cast2-receiver-resumed",function(){L5("yt-remote-receiver-resumed","cast-selector-receiver")})),V8.push(g.ep("yt-remote-cast2-session-change",Kra)),V8.push(g.ep("yt-remote-connection-change",function(m){m?s8(T8(),"YouTube TV"):X8()||(s8(null,null),qra())})),a=Y8(),b.isAuto&&(a.id+="#dial"),g.Mp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),U8(" -- with channel params: "+
g.tm(a)),Lra(a),c.start(),T8()||Mra())},Pra=function(){var a=Ora();
p8()&&g.Ts("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Ora=function(){var a=S8().Vc.$_gos();
var b=Z8();b&&$8()&&(U5(a,b)||a.push(b));return yqa(a)},a9=function(){var a=Qra();
!a&&p8()&&pra()&&(a={key:"cast-selector-receiver",name:pra()});return a},Qra=function(){var a=Ora(),b=Z8();
b||(b=X8());return g.Ya(a,function(c){return b&&O5(b,c.key)?!0:!1})},Z8=function(){var a=T8();
if(!a)return null;var b=S8().Qd();return V5(b,a)},Kra=function(a){U8("remote.onCastSessionChange_: "+R5(a));
if(a){var b=Z8();b&&b.id==a.id?s8(b.id,"YouTube TV"):(b&&b9(),c9(a,1))}else $8()&&b9()},b9=function(){q8()?n8().stopSession():l8("stopSession called before API ready.");
var a=$8();a&&(a.disconnect(1),d9(null))},e9=function(){var a=$8();
return!!a&&3!=a.getProxyState()},U8=function(a){K7("remote",a)},S8=function(){if(!f9){var a=g.x("yt.mdx.remote.screenService_");
f9=a?new P8(a):null}return f9},T8=function(){return g.x("yt.mdx.remote.currentScreenId_")},Rra=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Sra=function(){return g.x("yt.mdx.remote.connectData_")},W8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},$8=function(){return g.x("yt.mdx.remote.connection_")},d9=function(a){var b=$8();
W8(null);a||Rra("");g.Ga("yt.mdx.remote.connection_",a,void 0);R8&&((0,g.A)(R8,function(c){c(a)}),R8.length=0);
b&&!a?L5("yt-remote-connection-change",!1):!b&&a&&L5("yt-remote-connection-change",!0)},X8=function(){var a=g.Us();
if(!a)return null;var b=S8().Qd();return V5(b,a)},c9=function(a,b){Z8()&&Z8();
if(g9)h9=a;else{Rra(a.id);var c=new I8(Q8,a,Y8());c.connect(b,Sra());c.subscribe("beforeDisconnect",function(d){L5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){$8()&&d9(null)});
d9(c)}},Mra=function(){var a=X8();
a?(U8("Resume connection to: "+R5(a)),c9(a,0)):(e6(),qra(),U8("Skipping connecting because no session screen found."))},Jra=function(){var a=Y8();
if(g.Zb(a)){a=$5();var b=g.Ts("yt-remote-session-name")||"",c=g.Ts("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},Y8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Lra=function(a){a?(g.Ss("yt-remote-session-app",a.app),g.Ss("yt-remote-session-name",a.name)):(W5("yt-remote-session-app"),W5("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.H.call(this);
this.A=a;this.i=b;this.l=new g.es(this);g.J(this,this.l);this.l.L(b,"onCaptionsTrackListChanged",this.uJ);this.l.L(b,"captionschanged",this.sI);this.l.L(b,"captionssettingschanged",this.JA);this.l.L(b,"videoplayerreset",this.Ln);this.l.L(b,"mdxautoplaycancel",this.vC);this.R=this.l.L(b,"onVolumeChange",this.gz);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.sz,this);c.subscribe("remotePlayerChange",this.xk,this);c.subscribe("remoteQueueChange",this.Ln,this);c.subscribe("autoplayUpNext",this.Vy,
this);c.subscribe("previousNextChange",this.pz,this);c.subscribe("nowAutoplaying",this.lz,this);c.subscribe("autoplayDismissed",this.Uy,this);this.suggestion=null;this.G=new g.fC(64);this.o=new g.K(this.HA,500,this);g.J(this,this.o);this.B=new g.K(this.IA,1E3,this);g.J(this,this.B);this.J=new n6(this.VM,0,this);g.J(this,this.J);this.D={};this.S=new g.K(this.jB,1E3,this);g.J(this,this.S);this.I=new g.el(this.QF,1E3,this);g.J(this,this.I);this.N=g.Ha;this.JA();this.Ln();this.xk()},j9=function(a,b){a.A.Lc(b,
a.i.getVideoData().lengthSeconds)},Tra=function(a){j9(a,0);
a.o.stop();k9(a,new g.fC(64))},m9=function(a,b){if(l9(a)&&!a.F){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.gc(c,b));a.g.yA(a.i.getVideoData(1).videoId,c);a.D=C8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Le,H5(c));k9(a,new g.fC(1))},Ura=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{SQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.F=!1):(a.i.loadModule("captions"),a.F=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return C8(a.g).videoId==a.i.getVideoData(1).videoId},k9=function(a,b){a.B.stop();
var c=a.G;if(!g.lC(c,b)){var d=g.U(b,2);d!=g.U(a.G,2)&&g.jK(a.i,d);a.G=b;Vra(a.A,c,b)}},o9=function(){g.W.call(this,{C:"div",
H:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{C:"div",H:"ytp-mdx-popup-dialog-inner-content",K:[{C:"div",H:"ytp-mdx-popup-title",U:"Du \u00e4r utloggad"},{C:"div",H:"ytp-mdx-popup-description",U:"Videor du tittar p\u00e5 kan l\u00e4ggas till i tv:ns visningshistorik och p\u00e5verka tv-rekommendationerna. Undvik detta genom att avbryta och logga in p\u00e5 YouTube p\u00e5 datorn."},{C:"div",H:"ytp-mdx-privacy-popup-buttons",K:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Avbryt"},
{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],U:"Bekr\u00e4fta"}]}]}]});this.l=new g.fQ(this,250);g.J(this,this.l);this.D=this.i["ytp-mdx-privacy-popup-cancel"];this.L(this.D,"click",this.o);this.A=this.i["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},p9=function(a){g.W.call(this,{C:"div",
H:"ytp-remote",K:[{C:"div",H:"ytp-remote-display-status",K:[{C:"div",H:"ytp-remote-display-status-icon",K:[g.uP()]},{C:"div",H:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.fQ(this,250);g.J(this,this.l);this.o=a;this.L(a,"presentingplayerstatechange",this.A);Wra(this,g.fK(a))},Wra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.sN("Fel p\u00e5 $RECEIVER_NAME",c):g.mC(b)||g.U(b,4)?g.sN("Spelas upp p\u00e5 $RECEIVER_NAME",c):g.sN("Ansluten till $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.PT.call(this,"Spela upp p\u00e5",0,a,b);
this.l=a;this.D={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},r9=function(a){g.KK.call(this,a);
this.i={key:T5(),name:"Den h\u00e4r datorn"};this.A=null;this.o=[];this.I=this.g=null;this.F=[this.i];this.l=this.i;this.fk=new g.fC(64);this.J=0;this.Om=-1;this.B=null;if(!g.Fy(g.X(this.player))){a=this.player;var b=g.ZC(a);b&&(b=b.sn())&&(b=new q9(a,b),g.J(this,b));b=new p9(a);g.J(this,b);g.uK(a,b.element,4);this.B=new o9;g.J(this,this.B);g.uK(a,this.B.element,4);this.G=!!X8()}this.D=null},s9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",a.D),a.D=null)},Vra=function(a,
b,c){a.fk=c;
a.player.O("presentingplayerstatechange",new g.pD(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)b9();
else{var c;(c=!g.P(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.Qo("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.Qo("SESSION_INDEX")&&!g.Qo("LOGGED_IN")))||a.G||!a.B);c||g.Fy(g.X(a.player))||(g.mC(g.fK(a.player))?a.player.pauseVideo():(a.D=(0,g.y)(a.YL,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.B&&a.B.l.show(),$8()||(g9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();
if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Le,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=H5(c))&&(d.locationInfo=c);c=d}else c=null;U8("Connecting to: "+g.tm(b));"cast-selector-receiver"==b.key?(W8(c||null),q8()?n8().setLaunchParams(c||null):l8("setLaunchParams called before ready.")):!c&&e9()&&T8()==b.key?L5("yt-remote-connection-change",
!0):(b9(),W8(c||null),c=S8().Qd(),(c=V5(c,b.key))&&c9(c,1))}},H6={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},G6={"'":"\\'"},Xra={},wqa={QN:"atp",eQ:"ska",TP:"que",uP:"mus",dQ:"sus",MO:"dsp",aQ:"seq"};
M5.prototype.eg=function(){var a=new M5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var f6,Z5="",Eqa=h6("loadCastFramework")||h6("loadCastApplicationFramework"),mra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(n6,g.H);g.h=n6.prototype;g.h.pD=function(a){this.o=arguments;this.g=!1;this.Ca?this.l=(0,g.D)()+this.Wc:this.Ca=g.cl(this.A,this.Wc)};
g.h.stop=function(){this.Ca&&(g.w.clearTimeout(this.Ca),this.Ca=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.B.apply(null,this.o)))};
g.h.V=function(){this.stop();n6.bb.V.call(this)};
g.h.qD=function(){this.l?(this.Ca=g.cl(this.A,this.l-(0,g.D)()),this.l=null):(this.Ca=null,this.i?this.g=!0:(this.g=!1,this.B.apply(null,this.o)))};p6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
p6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};q6.prototype.g=null;q6.prototype.getOptions=function(){var a;(a=this.g)||(a={},s6(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Sa(r6,q6);u9=new r6;g.h=u6.prototype;g.h.Xg=null;g.h.ze=!1;g.h.Ti=null;g.h.At=null;g.h.Di=null;g.h.Yh=null;g.h.Wf=null;g.h.Bg=null;g.h.ph=null;g.h.sc=null;g.h.bl=0;g.h.De=null;g.h.Eo=null;g.h.ng=null;g.h.Kj=-1;g.h.rA=!0;g.h.Mg=!1;g.h.zq=0;g.h.Tn=null;var B6={},z6={};g.h=u6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.hM=function(a){a=a.target;var b=this.Tn;b&&3==Y6(a)?b.Gj():this.rB(a)};
g.h.rB=function(a){try{if(a==this.sc)a:{var b=Y6(this.sc),c=this.sc.A,d=this.sc.getStatus();if(g.Kd&&!g.nd(10)||g.Md&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.cg&&!b7(this.sc))break a;this.Mg||4!=b||7==c||(8==c||0>=d?this.g.ye(3):this.g.ye(2));L6(this);var e=this.sc.getStatus();this.Kj=e;var f=b7(this.sc);(this.ze=200==e)?(4==b&&D6(this),this.A?(F6(this,b,f),g.cg&&this.ze&&3==b&&(this.ca.ea(this.i,"tick",this.bM),this.i.start())):C6(this,f),this.ze&&!this.Mg&&(4==b?this.g.In(this):(this.ze=
!1,y6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ng=3,A6(13)):(this.ng=0,A6(14)),D6(this),E6(this))}}catch(k){this.sc&&b7(this.sc)}finally{}};
g.h.bM=function(){var a=Y6(this.sc),b=b7(this.sc);this.bl<b.length&&(L6(this),F6(this,a,b),this.ze&&4!=a&&y6(this))};
g.h.xL=function(a){K6((0,g.y)(this.wL,this,a),0)};
g.h.wL=function(a){this.Mg||(L6(this),C6(this,a),y6(this))};
g.h.Az=function(a){K6((0,g.y)(this.vL,this,a),0)};
g.h.vL=function(a){this.Mg||(D6(this),this.ze=a,this.g.In(this),this.g.ye(4))};
g.h.cancel=function(){this.Mg=!0;D6(this)};
g.h.HL=function(){this.Ti=null;var a=(0,g.D)();0<=a-this.At?(2!=this.Yh&&this.g.ye(3),D6(this),this.ng=2,A6(18),E6(this)):J6(this,this.At-a)};
g.h.getLastError=function(){return this.ng};g.h=P6.prototype;g.h.xq=null;g.h.Gd=null;g.h.Un=!1;g.h.yw=null;g.h.dm=null;g.h.er=null;g.h.yq=null;g.h.he=null;g.h.Af=-1;g.h.Jj=null;g.h.fj=null;g.h.connect=function(a){this.yq=a;a=Q6(this.g,null,this.yq);A6(3);this.yw=(0,g.D)();var b=this.g.F;null!=b?(this.Jj=b[0],(this.fj=b[1])?(this.he=1,R6(this)):(this.he=2,T6(this))):(G5(a,"MODE","init"),this.Gd=new u6(this,void 0,void 0,void 0),this.Gd.Xg=this.xq,x6(this.Gd,a,!1,null,!0),this.he=0)};
g.h.wC=function(a){if(a)this.he=2,T6(this);else{A6(4);var b=this.g;b.Ie=b.dg.Af;v7(b,9)}a&&this.ye(2)};
g.h.Pp=function(a){return this.g.Pp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.Af=-1};
g.h.xw=function(){return!1};
g.h.uz=function(a,b){this.Af=a.Kj;if(0==this.he)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ie=this.Af;v7(c,2);return}this.Jj=c[0];this.fj=c[1]}else c=this.g,c.Ie=this.Af,v7(c,2);else if(2==this.he)if(this.Un)A6(7),this.er=(0,g.D)();else if("11111"==b){if(A6(6),this.Un=!0,this.dm=(0,g.D)(),c=this.dm-this.yw,!g.Kd||g.nd(10)||500>c)this.Af=200,this.Gd.cancel(),A6(12),S6(this.g,this,!0)}else A6(8),this.dm=this.er=(0,g.D)(),this.Un=!1};
g.h.In=function(){this.Af=this.Gd.Kj;if(this.Gd.ze)0==this.he?this.fj?(this.he=1,R6(this)):(this.he=2,T6(this)):2==this.he&&((!g.Kd||g.nd(10)?!this.Un:200>this.er-this.dm)?(A6(11),S6(this.g,this,!1)):(A6(12),S6(this.g,this,!0)));else{0==this.he?A6(9):2==this.he&&A6(10);var a=this.g;this.Gd.getLastError();a.Ie=this.Af;v7(a,2)}};
g.h.Ok=function(){return this.g.Ok()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ye=function(a){this.g.ye(a)};g.Sa(U6,g.rk);var Jqa=/^https?$/i,Yra=["POST","PUT"];g.h=U6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.A=0;this.Z=b;this.R=!1;this.i=!0;this.g=this.N?t6(this.N):t6(u9);this.S=this.N?this.N.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.y)(this.zw,this);try{K5(Z6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){K5(Z6(this,"Error opening Xhr: "+f.message));X6(this,f);return}a=c||"";
var e=this.headers.clone();d&&sqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Pd(),Iqa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(Yra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{a7(this),0<this.B&&(this.J=Hqa(this.g),K5(Z6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.B,this.g.ontimeout=(0,g.y)(this.Aw,this)):this.G=g.cl(this.Aw,this.B,this)),K5(Z6(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){K5(Z6(this,"Send error: "+f.message)),X6(this,f)}};
g.h.Aw=function(){"undefined"!=typeof g.BY&&this.g&&(this.l="Timed out after "+this.B+"ms, aborting",this.A=8,Z6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(Z6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),W6(this))};
g.h.V=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),W6(this,!0));U6.bb.V.call(this)};
g.h.zw=function(){this.ga()||(this.aa||this.D||this.o?$6(this):this.wK())};
g.h.wK=function(){$6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<Y6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.u(this.l)?this.l:String(this.l)};g.h=c7.prototype;g.h.sj=null;g.h.Cd=null;g.h.Rb=null;g.h.wq=null;g.h.gm=null;g.h.Gu=null;g.h.xm=null;g.h.rk=0;g.h.MH=0;g.h.Tc=null;g.h.lg=null;g.h.mf=null;g.h.Rg=null;g.h.dg=null;g.h.Co=null;g.h.li=-1;g.h.jx=-1;g.h.Ie=-1;g.h.Rh=0;g.h.Kh=0;g.h.Ng=8;var w7=new g.rk;g.Sa(d7,g.Tj);g.Sa(e7,g.Tj);g.Sa(f7,g.Tj);g.h=c7.prototype;g.h.connect=function(a,b,c,d,e){A6(0);this.wq=b;this.sj=c||{};d&&g.Da(e)&&(this.sj.OSID=d,this.sj.OAID=e);this.B?(K6((0,g.y)(this.av,this,a),100),l7(this)):this.av(a)};
g.h.av=function(a){this.dg=new P6(this);this.dg.xq=null;this.dg.i=this.A;this.dg.connect(a)};
g.h.xw=function(){return 0==this.g};
g.h.zz=function(a){this.lg=null;q7(this,a)};
g.h.yz=function(){this.mf=null;this.Rb=new u6(this,this.l,"rpc",this.D);this.Rb.Xg=null;this.Rb.zq=0;var a=this.Gu.clone();E5(a,"RID","rpc");E5(a,"SID",this.l);E5(a,"CI",this.Co?"0":"1");E5(a,"AID",this.li);h7(this,a);if(!g.Kd||g.nd(10))E5(a,"TYPE","xmlhttp"),x6(this.Rb,a,!0,this.xm,!1);else{E5(a,"TYPE","html");var b=this.Rb,c=!!this.xm;b.Yh=3;b.Wf=F5(a.clone());I6(b,c)}};
g.h.uz=function(a,b){if(0!=this.g&&(this.Rb==a||this.Cd==a))if(this.Ie=a.Kj,this.Cd==a&&3==this.g)if(7<this.Ng){try{var c=this.A.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.mf){if(this.Rb)if(this.Rb.Di+3E3<this.Cd.Di)m7(this),this.Rb.cancel(),this.Rb=null;else break a;t7(this);A6(19)}}else this.jx=c[1],0<this.jx-this.li&&37500>c[2]&&this.Co&&0==this.Kh&&!this.Rg&&(this.Rg=K6((0,g.y)(this.oI,this),6E3));else v7(this,11)}else b!=Xra.nO.g&&v7(this,11);else if(this.Rb==a&&
m7(this),!g.xb(b)){c=this.A.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.li=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.xm=e[2],e=e[3],null!=e?this.Ng=e:this.Ng=6,this.g=3,this.Tc&&this.Tc.Uu(),this.Gu=Q6(this,this.Ok()?this.xm:null,this.wq),r7(this)):"stop"==e[0]&&v7(this,7):3==this.g&&("stop"==e[0]?v7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Tu(e),this.Kh=0)}}};
g.h.oI=function(){null!=this.Rg&&(this.Rg=null,this.Rb.cancel(),this.Rb=null,t7(this),A6(20))};
g.h.In=function(a){if(this.Rb==a){m7(this);this.Rb=null;var b=2}else if(this.Cd==a)this.Cd=null,b=1;else return;this.Ie=a.Kj;if(0!=this.g)if(a.ze)1==b?(b=(0,g.D)()-a.Di,w7.dispatchEvent(new e7(w7,a.ph?a.ph.length:0,b,this.Rh)),k7(this),this.o.length=0):r7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ie)){if(d=1==b)this.Cd||this.lg||1==this.g||2<=this.Rh?d=!1:(this.lg=K6((0,g.y)(this.zz,this,a),s7(this,this.Rh)),this.Rh++,d=!0);d=!(d||2==b&&t7(this))}if(d)switch(c){case 1:v7(this,
5);break;case 4:v7(this,10);break;case 3:v7(this,6);break;case 7:v7(this,12);break;default:v7(this,2)}}};
g.h.RC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.LM=function(a){a?A6(2):(A6(1),u7(this,8))};
g.h.Pp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new U6;a.T=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.ye=function(a){w7.dispatchEvent(new f7(w7,a))};
g.h.Ok=function(){return!(!g.Kd||g.nd(10))};
g.h=x7.prototype;g.h.Uu=function(){};
g.h.Tu=function(){};
g.h.Su=function(){};
g.h.Cp=function(){};
g.h.Vv=function(){return{}};
g.h.isActive=function(){return!0};g.h=y7.prototype;g.h.isEmpty=function(){return g.bb(this.g)&&g.bb(this.i)};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.ena)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.Ec=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Sa(z7,g.H);g.h=z7.prototype;g.h.pL=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.vn(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.Sa(A7,x7);g.h=A7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.If=function(a){return this.l.Yg(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.Ci(this.l),B7(this),g.Ci(this.i),this.i=null)};
g.h.ga=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.G="";this.i.stop();this.A=a||null;this.o=b||0;a=this.I+"/test";b=this.I+"/bind";var d=new c7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.B,e.l,e.li):c?this.g.connect(a,b,this.B,c.sessionId,c.arrayId):this.g.connect(a,b,this.B)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):C7(this)&&n7(this.g,c)};
g.h.Uu=function(){this.i.reset();this.A=null;this.o=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)n7(this.g,a[b])}this.O("handlerOpened")};
g.h.Su=function(a){var b=2==a&&401==this.g.Ie;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.Cp=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Vv=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.o&&(a.ui=""+this.o);0!=this.F&&(a.ui=""+this.F);this.A&&g.gc(a,this.A);return a};
g.h.Tu=function(a){"S"==a[0]?this.G=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),j7(this.g)):this.O("handlerMessage",new Lqa(a[0],a[1]))};
g.h.rM=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.Cd&&b++;0==b&&this.connect(this.A,this.o)};D7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
D7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
D7.prototype.A=function(a){a(Error("request timed out"))};var Rqa=(0,g.D)(),I7=null,M7=Array(50),L7=-1,N7=!1;g.Sa(O7,g.O);O7.prototype.Qd=function(){return this.g};
O7.prototype.contains=function(a){return!!U5(this.g,a)};
O7.prototype.get=function(a){return a?V5(this.g,a):null};
O7.prototype.info=function(a){K7(this.D,a)};g.t(Q7,g.O);g.h=Q7.prototype;g.h.start=function(){!this.g&&isNaN(this.Ca)&&this.uB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ca)||(g.$o(this.Ca),this.Ca=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.uB=function(){this.Ca=NaN;this.g=g.Vp(E7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.y)(this.pN,this),onError:(0,g.y)(this.oN,this),Ud:(0,g.y)(this.qN,this)})};
g.h.pN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new N5(c))};
g.h.oN=function(a){this.g=null;a.status&&404==a.status?this.i>=Zra.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=Zra[this.i],this.Ca=g.Yo((0,g.y)(this.uB,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.qN=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var Zra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(S7,O7);g.h=S7.prototype;g.h.start=function(){R7(this)&&this.O("screenChange");!g.Ts("yt-remote-lounge-token-expiration")&&Uqa(this);g.$o(this.i);this.i=g.Yo((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){R7(this);P7(this,a);T7(this,!1);this.O("screenChange");b(a);a.token||Uqa(this)};
g.h.remove=function(a,b){var c=R7(this);Tqa(this,a)&&(T7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.yo=function(a,b,c,d){var e=R7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,T7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.V=function(){g.$o(this.i);S7.bb.V.call(this)};
g.h.AD=function(a){R7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}T7(this,!b);b&&K7(this.D,"Missed "+b+" lounge tokens.")};
g.h.zD=function(a){K7(this.D,"Requesting lounge tokens failed: "+a)};g.t(V7,g.O);g.h=V7.prototype;g.h.start=function(){var a=parseInt(g.Ts("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?X7(this):(this.o=(0,g.D)()+3E5,g.Ss("yt-remote-fast-check-period",this.o),this.Fs())};
g.h.isEmpty=function(){return g.Zb(this.g)};
g.h.update=function(){U7("Updating availability on schedule.");var a=this.B(),b=g.Mb(this.g,function(c,d){return c&&!!V5(a,d)},this);
W7(this,b)};
g.h.V=function(){g.$o(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.Fs=function(){g.$o(this.l);this.l=NaN;this.i&&this.i.abort();var a=Xqa(this);if(I5(a)){var b=E7(this.A,"/pairing/get_screen_availability");this.i=F7(this.A,b,{lounge_token:g.Tb(a).join(",")},(0,g.y)(this.SK,this,a),(0,g.y)(this.RK,this))}else W7(this,{}),X7(this)};
g.h.SK=function(a,b){this.i=null;var c=g.Tb(Xqa(this));if(g.sb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;W7(this,d);X7(this)}else this.Ib("Changing Screen set during request."),this.Fs()};
g.h.RK=function(a){this.Ib("Screen availability failed: "+a);this.i=null;X7(this)};
g.h.Ib=function(a){K7("OnlineScreenService",a)};g.Sa(Y7,O7);g.h=Y7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.yo=function(a,b,c,d){this.l.contains(a)?this.l.yo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K7(this.D,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.gb(this.g,(0,g.Wd)(this.o,function(b){return!this.contains(b)},this))};
g.h.vB=function(){return(0,g.Wd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.wB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new Q7(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.Ci(f);d(Z7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ci(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.sN=function(a,b,c,d){g.Vp(E7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new N5(f.screen||{});if(!k.name||ara(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);ara(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(Z7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
Ud:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ci(this.l);g.Ci(this.i);Y7.bb.V.call(this)};
g.h.ID=function(){bra(this);this.O("screenChange");this.i.update()};
Y7.prototype.dispose=Y7.prototype.dispose;g.Sa(a8,g.O);g.h=a8.prototype;g.h.Kn=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Td=function(a){this.ga()||(a&&b8(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){K7(this.S,a)};
g.h.yB=function(){return null};
g.h.Os=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){b8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Os("");a8.bb.V.call(this)};g.Sa(c8,a8);g.h=c8.prototype;g.h.Ns=function(a){if(this.g){if(this.g==a)return;b8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.B);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A)}this.g=a;this.g.addUpdateListener(this.B);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.A);dra(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.tm(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Td()},this),(0,g.y)(function(){this.Td(Error("Failed to stop receiver app."))},this)):this.Td(Error("Stopping cast device witout session."))};
g.h.Os=g.Ha;g.h.V=function(){this.info("disposeInternal");g.$o(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.B),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A));this.g=null;c8.bb.V.call(this)};
g.h.SL=function(a,b){if(!this.ga())if(b){var c=o6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.tm(c));switch(d){case "mdxSessionStatus":cra(this,c.screenId);break;default:b8(this,"Unknown youtube message: "+d)}}else b8(this,"Unable to parse message.")}else b8(this,"No data in message.")};
g.h.nw=function(a,b,c,d){$qa(this.G,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(b8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Yo((0,g.y)(this.nw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.yB=function(){return this.g};
g.h.tN=function(a){this.ga()||a||(b8(this,"Cast session died."),this.Td())};g.Sa(d8,a8);g.h=d8.prototype;g.h.Ns=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.mi=function(a){this.A=a;this.D()};
g.h.stop=function(){this.g();this.g=g.Ha;g.$o(this.B);this.o?this.o.stop((0,g.y)(this.Td,this,null),(0,g.y)(this.Td,this,"Failed to stop DIAL device.")):this.Td()};
g.h.V=function(){this.g();this.g=g.Ha;g.$o(this.B);this.o&&this.o.removeUpdateListener(this.J);this.o=null;d8.bb.V.call(this)};
g.h.wN=function(a){this.ga()||a||(b8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Td())};
g.h.Lq=function(a){this.I=T5();if(this.A){var b=new chrome.cast.DialLaunchResponse(!0,fra(this));a(b);era(this)}else this.D=(0,g.y)(function(){g.$o(this.B);this.D=g.Ha;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,fra(this));a(c);era(this)},this),this.B=g.Yo((0,g.y)(function(){this.D()},this),100)};
g.h.eE=function(a,b,c){$qa(this.G,this.F.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Kn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Lq(b,c)},this),(0,g.y)(function(d){b8(this,"Failed to get DIAL screen: "+d);
this.Lq(b,c)},this))};g.Sa(e8,a8);e8.prototype.stop=function(){this.Td()};
e8.prototype.Ns=g.Ha;e8.prototype.mi=function(){g.$o(this.g);this.g=NaN;var a=V5(this.G.Qd(),this.i.label);a?this.Kn(a):this.Td(Error("No such screen"))};
e8.prototype.V=function(){g.$o(this.g);this.g=NaN;e8.bb.V.call(this)};g.Sa(f8,g.O);g.h=f8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.y)(this.BK,this);c=new chrome.cast.ApiConfig(c,(0,g.y)(this.wz,this),f,d,e);c.customDialLaunchCallback=(0,g.y)(this.QI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.o),Oqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.xB,this)),this.l=hra(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(k){this.Ib("Failed to set initial custom receivers: "+g.tm(k))},this)),this.O("yt-remote-cast2-availability-change",h8(this)),b(!0))},this),(0,g.y)(function(k){this.Ib("Failed to initialize API: "+g.tm(k));
b(!1)},this))};
g.h.zM=function(a,b){g8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)g8("Unsetting old screen status: "+this.g.i.friendlyName),i8(this,null)}if(a&&b){if(!this.g){c=V5(this.i.Qd(),a);if(!c){g8("setConnectedScreenStatus: Unknown screen.");return}var d=gra(this,c);d||(g8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Ib("Failed to set initial custom receivers: "+g.tm(e))},this)));
g8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);i8(this,new e8(this.i,d),!0)}this.g.Os(b)}else g8("setConnectedScreenStatus: no screen.")};
g.h.AM=function(a){this.ga()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Ib("Setting connection data without a session")};
g.h.vN=function(){this.ga()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),i8(this,null)):g8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.wz,this),(0,g.y)(this.YK,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.xB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.x("yt.mdx.remote.debug.handlers_")||[],G7);g.Ci(this.g);f8.bb.V.call(this)};
g.h.Ib=function(a){K7("Controller",a)};
g.h.xz=function(a,b){this.g==a&&(b||i8(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.xK=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),g8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)g8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{g8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:i8(this,
new e8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:i8(this,new d8(this.i,a,this.B));break;case chrome.cast.ReceiverType.CAST:i8(this,new c8(this.i,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.QI=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return g8("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);i8(this,new d8(this.i,b,this.B))}b=this.g;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.eE,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Lq,b))};
g.h.wz=function(a){if(!this.ga()){g8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)g8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),i8(this,new c8(this.i,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=V5(this.i.Qd(),c.label);d&&O5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(g8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ci(this.g),this.g=new c8(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.xz,this,this.g)),this.g.mi(null));this.g.Ns(a)}}};
g.h.uN=function(){return this.g?this.g.yB():null};
g.h.YK=function(a){this.ga()||(this.Ib("Failed to estabilish a session: "+g.tm(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&i8(this,null))};
g.h.BK=function(a){g8("Receiver availability updated: "+a);if(!this.ga()){var b=h8(this);this.A=a==chrome.cast.ReceiverAvailability.AVAILABLE;h8(this)!=b&&this.O("yt-remote-cast2-availability-change",h8(this))}};
g.h.xB=function(){this.ga()||(this.l=hra(this),g8("Updating custom receivers: "+g.tm(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Ib("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",h8(this)))};
f8.prototype.setLaunchParams=f8.prototype.AM;f8.prototype.setConnectedScreenStatus=f8.prototype.zM;f8.prototype.stopSession=f8.prototype.vN;f8.prototype.getCastSession=f8.prototype.uN;f8.prototype.requestSession=f8.prototype.requestSession;f8.prototype.init=f8.prototype.init;f8.prototype.dispose=f8.prototype.dispose;var o8=[];t8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";u8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Je=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.B=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.F=a.duration,this.G=a.loadedTime,this.l=a.liveIngestionTime,this.A=
!isNaN(this.l))};
t8.prototype.isAdPlaying=function(){return 1081==this.playerState};
t8.prototype.getDuration=function(){return this.A?this.F+v8(this):this.F};
t8.prototype.clone=function(){return new t8(z8(this))};g.t(B8,g.O);g.h=B8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,H8(this,"play")):G8(this,"play"),F8(this,1,x8(C8(this))),this.O("remotePlayerChange")):D8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,H8(this,"pause")):G8(this,"pause"),F8(this,2,x8(C8(this))),this.O("remotePlayerChange")):D8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=C8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,H8(this,"seekTo",{newTime:a}))}else G8(this,"seekTo",{newTime:a});F8(this,3,a);this.O("remotePlayerChange")}else D8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,H8(this,"stopVideo")):G8(this,"stopVideo");var a=C8(this);a.index=-1;a.videoId="";u8(a);E8(this,a);this.O("remotePlayerChange")}else D8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=C8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){K7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){K7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);G8(this,"setVolume",e)}c.muted=b;c.volume=a;E8(this,c)}else D8(this,g.Qa(this.setVolume,a,b))};
g.h.yA=function(a,b){if(1==this.g){var c=C8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.tm(b.style),g.gc(d,c.g));G8(this,"setSubtitlesTrack",d);E8(this,c)}else D8(this,g.Qa(this.yA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();G8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=C8(this);d.audioTrackId=c;E8(this,d)}else D8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=C8(this);c=c||0;var m={videoId:a,currentIndex:c};y8(l,a,c);g.Da(b)&&(w8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.tm(k));G8(this,"setPlaylist",m);d||E8(this,l)};
g.h.Pn=function(a,b){if(1==this.g){if(a&&b){var c=C8(this);y8(c,a,b);E8(this,c)}G8(this,"previous")}else D8(this,g.Qa(this.Pn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=C8(this);y8(c,a,b);E8(this,c)}G8(this,"next")}else D8(this,g.Qa(this.nextVideo,a,b))};
g.h.yv=function(){1==this.g?G8(this,"dismissAutoplay"):D8(this,this.yv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){ura(this);this.o=null;this.A.clear();A8(this,null);g.O.prototype.V.call(this)};
g.h.Dt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.A.isEmpty();)b=a=this.A,g.bb(b.g)&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.uK=function(a,b){this.O(a,b)};
g.h.uI=function(a){if(!a)this.vk(null),A8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=C8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,E8(this,b)}};
g.h.vk=function(a){K7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.F);if(this.i=a)this.i.addUpdateListener(this.F),vra(this),this.O("remotePlayerChange")};
g.h.tI=function(a){a?(vra(this),this.O("remotePlayerChange")):this.vk(null)};
g.h.it=function(){G8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.II=function(){var a=rra();a&&A8(this,a)};
g.h.Ib=function(a){K7("CP",a)};g.t(I8,g.O);g.h=I8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;w8(this.Oa,m);this.o="UNSUPPORTED";J8("Connecting with setPlaylist and params: "+g.tm(l));this.g.connect({method:"setPlaylist",
params:g.tm(l)},a,b6())}else J8("Connecting without params"),this.g.connect({},a,b6());xra(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),K8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){L8(this);N8(this);M8(this);g.$o(this.D);this.D=NaN;g.$o(this.F);this.F=NaN;this.l=null;g.rr(this.S);this.S.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.B=this.i=this.Oa=this.g=null};
g.h.tD=function(){this.Oh(2)};
g.h.yI=function(){J8("Channel opened");this.J&&(this.J=!1,M8(this),this.I=g.Yo((0,g.y)(function(){J8("Timing out waiting for a screen.");this.Oh(1)},this),15E3));
Cqa(Mqa(this.g),this.N)};
g.h.vI=function(){J8("Channel closed");isNaN(this.A)?e6(!0):e6();this.dispose()};
g.h.wI=function(a){e6();isNaN(this.Aj())?(J8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,J8("Channel error: "+a+" with reconnection in "+this.Aj()+" ms"),K8(this,2))};
g.h.xI=function(a){a.params?J8("Received: action="+a.action+", params="+g.tm(a.params)):J8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=o6(a.params.devices);this.i=(0,g.B)(a,function(c){return new M5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Ara(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Ara(this,!1);break;case "remoteConnected":var b=new M5(o6(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||pqa(this.i,b);
break;case "remoteDisconnected":b=new M5(o6(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Cra(this,a);break;case "nowPlaying":Era(this,a);break;case "onStateChange":Dra(this,a);break;case "onAdStateChange":Fra(this,a);break;case "onVolumeChanged":Gra(this,a);break;case "onSubtitlesTrackChanged":Bra(this,a);break;case "nowAutoplaying":Hra(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.O("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":Ira(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:J8("Unrecognized action: "+a.action)}};
g.h.oM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&O8(this,"getNowPlaying")}};
g.h.jD=function(){var a=3;this.ga()||(a=0,isNaN(this.Aj())?C7(this.g)&&isNaN(this.A)&&(a=1):a=2);return a};
g.h.Oh=function(a){J8("Disconnecting with "+a);L8(this);this.O("beforeDisconnect",a);1==a&&e6();B7(this.g,a);this.dispose()};
g.h.iD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),y8(a,this.l,a.index));return z8(a)};
g.h.BM=function(a){var b=new t8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.$o(this.D),this.D=g.Yo((0,g.y)(this.oM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&x8(this.Oa)==x8(b)&&g.tm(this.Oa.g)==g.tm(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.A)(c,function(d){this.O(d)},this)};
g.h.lw=function(){var a=this.g.B.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Aj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.cD=function(){return this.o||"UNSUPPORTED"};
g.h.dD=function(){return this.B||""};
g.h.nN=function(){if(!isNaN(this.Aj())){var a=this.g.i;g.wn(a.g);a.start()}};
g.h.wM=function(a,b){O8(this,a,b);zra(this)};
I8.prototype.subscribe=I8.prototype.subscribe;I8.prototype.unsubscribeByKey=I8.prototype.If;I8.prototype.getProxyState=I8.prototype.jD;I8.prototype.disconnect=I8.prototype.Oh;I8.prototype.getPlayerContextData=I8.prototype.iD;I8.prototype.setPlayerContextData=I8.prototype.BM;I8.prototype.getOtherConnectedRemoteId=I8.prototype.lw;I8.prototype.getReconnectTimeout=I8.prototype.Aj;I8.prototype.getAutoplayMode=I8.prototype.cD;I8.prototype.getAutoplayVideoId=I8.prototype.dD;I8.prototype.reconnect=I8.prototype.nN;
I8.prototype.sendMessage=I8.prototype.wM;g.t(P8,O7);g.h=P8.prototype;g.h.Qd=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.add=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.yo=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Vc.$_ubk(this.i[a]);this.i.length=0;this.Vc=null;O7.prototype.V.call(this)};
g.h.rN=function(){this.O("screenChange")};
g.h.ZJ=function(){this.O("onlineScreenChange")};
Y7.prototype.$_st=Y7.prototype.start;Y7.prototype.$_gspc=Y7.prototype.sN;Y7.prototype.$_gsppc=Y7.prototype.wB;Y7.prototype.$_c=Y7.prototype.contains;Y7.prototype.$_g=Y7.prototype.get;Y7.prototype.$_a=Y7.prototype.add;Y7.prototype.$_un=Y7.prototype.yo;Y7.prototype.$_r=Y7.prototype.remove;Y7.prototype.$_gs=Y7.prototype.Qd;Y7.prototype.$_gos=Y7.prototype.vB;Y7.prototype.$_s=Y7.prototype.subscribe;Y7.prototype.$_ubk=Y7.prototype.If;var h9=null,g9=!1,Q8=null,R8=null,f9=null,V8=[];g.t(i9,g.H);g.h=i9.prototype;
g.h.V=function(){g.H.prototype.V.call(this);this.o.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.sz,this);this.g.unsubscribe("remotePlayerChange",this.xk,this);this.g.unsubscribe("remoteQueueChange",this.Ln,this);this.g.unsubscribe("autoplayUpNext",this.Vy,this);this.g.unsubscribe("previousNextChange",this.pz,this);this.g.unsubscribe("nowAutoplaying",this.lz,this);this.g.unsubscribe("autoplayDismissed",this.Uy,this);this.g=this.A=null};
g.h.Qx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!C8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==C8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Gj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.sI=function(a){this.J.pD(a)};
g.h.VM=function(a){this.Qx("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.JA=function(){var a=this.i.getOption("captions","track");g.Zb(a)||m9(this,a)};
g.h.gz=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.xk,this);var b=Math.round(a.volume);a=!!a.muted;var c=C8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.S.start();this.g.subscribe("remotePlayerChange",this.xk,this)}};
g.h.uJ=function(){g.Zb(this.D)||Ura(this,this.D);this.F=!1};
g.h.sz=function(a,b){this.B.stop();2==b&&this.IA()};
g.h.xk=function(){if(l9(this)){this.o.stop();var a=C8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.A.Om=1;break;case 1082:case 1083:this.A.Om=0;break;default:this.A.Om=-1}switch(a.playerState){case 1081:case 1:k9(this,new g.fC(8));this.HA();break;case 1085:case 3:k9(this,new g.fC(9));break;case 1083:case 0:k9(this,new g.fC(2));this.I.stop();j9(this,this.i.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.fC(4));break;case 2:k9(this,new g.fC(4));j9(this,x8(a));
break;case -1:k9(this,new g.fC(64));break;case -1E3:k9(this,new g.fC(128,{errorCode:"mdx.remoteerror",errorMessage:"Det h\u00e4r videoklippet \u00e4r inte tillg\u00e4ngligt f\u00f6r fj\u00e4rruppspelning."}))}a=C8(this.g).g;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,Ura(this,a));a=C8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.S.isActive()||this.jB()}else Tra(this)};
g.h.pz=function(){this.i.O("mdxpreviousnextchange")};
g.h.Ln=function(){l9(this)||Tra(this)};
g.h.vC=function(){this.g.yv()};
g.h.Vy=function(a){a&&!g.P(g.X(this.i).experiments,"disable_legacy_desktop_remote_queue")&&(a=g.Vp("/watch_queue_ajax",{method:"GET",td:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.AL,this)}))&&(this.N=(0,g.y)(a.abort,a))};
g.h.AL=function(a,b){var c=new g.PA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.lz=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.Uy=function(){this.i.O("mdxautoplaycanceled")};
g.h.QF=function(a,b){-1==C8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.jB=function(){if(l9(this)){var a=C8(this.g);this.l.Ra(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.L(this.i,"onVolumeChange",this.gz)}};
g.h.HA=function(){this.o.stop();if(!this.g.ga()){var a=C8(this.g);1==a.playerState&&k9(this,new g.fC(8));j9(this,x8(a));this.o.start()}};
g.h.IA=function(){this.B.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.B.start()};g.t(o9,g.W);o9.prototype.o=function(){L5("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.B=function(){L5("mdx-privacy-popup-confirm");this.l.hide()};g.t(p9,g.W);p9.prototype.A=function(a){Wra(this,a.state)};g.t(q9,g.PT);q9.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.D=g.ub(a,this.B,this),g.RT(this,(0,g.B)(a,this.B)),a=this.l.getOption("remote","currentReceiver"),this.me(this.B(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.B=function(a){return a.key};
q9.prototype.xe=function(a){return"cast-selector-receiver"==a?"Casta \u2026":this.D[a].name};
q9.prototype.Jc=function(a){g.PT.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.D[a]);this.o.nb()};g.t(r9,g.KK);g.h=r9.prototype;
g.h.create=function(){Nra(g.vy(g.X(this.player)));this.o.push(g.ep("yt-remote-before-disconnect",this.pI,this));this.o.push(g.ep("yt-remote-connection-change",this.CK,this));this.o.push(g.ep("yt-remote-receiver-availability-change",this.qz,this));this.o.push(g.ep("yt-remote-auto-connect",this.AK,this));this.o.push(g.ep("yt-remote-receiver-resumed",this.zK,this));this.o.push(g.ep("mdx-privacy-popup-confirm",this.eM,this));this.o.push(g.ep("mdx-privacy-popup-cancel",this.dM,this));this.qz()};
g.h.load=function(){this.player.cancelPlayback();g.KK.prototype.load.call(this);this.A=new i9(this,this.player,this.g);var a=(a=Sra())?a.currentTime:0;var b=e9()?new B8($8(),void 0):null;0==a&&b&&(a=x8(C8(b)));0!=a&&this.Lc(a);Vra(this,this.fk,this.fk);g.TX(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.Di(this.A,this.g);this.g=this.A=null;g.KK.prototype.unload.call(this);g.TX(this.player.app,5);s9(this)};
g.h.V=function(){g.fp(this.o);g.KK.prototype.V.call(this)};
g.h.We=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.Qx.apply(this.A,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Om};
g.h.lD=function(){return this.loaded?this.A.suggestion:null};
g.h.Je=function(){return this.g?C8(this.g).Je:!1};
g.h.hasNext=function(){return this.g?C8(this.g).hasNext:!1};
g.h.Lc=function(a,b){this.J=a||0;this.player.O("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=C8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ac():!a.isAdPlaying()&&this.player.ac(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.l+v8(a):a.l,isAtLiveHead:1>=(a.A?a.i+v8(a):a.i)-this.getCurrentTime(),loaded:a.G,seekableEnd:a.A?a.i+v8(a):a.i,seekableStart:0<a.o?a.o+
v8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Pn=function(){this.g&&this.g.Pn()};
g.h.pI=function(a){1==a&&(this.I=this.g?C8(this.g):null)};
g.h.CK=function(){var a=e9()?new B8($8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.I=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Ci(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,x8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.qz=function(){this.F=[this.i].concat(Pra());var a=a9()||this.i;t9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.YL=function(a){!this.G&&g.rD(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.AK=function(){var a=a9();t9(this,a)};
g.h.zK=function(){this.l=a9()};
g.h.eM=function(){this.G=!0;s9(this);g9=!1;h9&&c9(h9,1);h9=null};
g.h.dM=function(){this.G=!1;s9(this);t9(this,this.i);this.l=this.i;g9=!1;h9=null;this.player.playVideo()};
g.h.uc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?r8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&r8(),!0):!1}};
g.h.it=function(){this.g.it()};
g.h.Db=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.hV.remote=r9;})(_yt_player);
